shared/base/view.js, test/shared/base/view.test.js
basically what the title says.
it's a quick update of: https://github.com/rendrjs/rendr/pull/304 - and adds tests around it.
=> move the refresh to live in parseOptions to make sure it works after hydration

shared/base/view.js, test/shared/base/view.test.js
When parseModelAndCollection is called by the rendr-handlebars `view` method on the client-side there is not an app option present, so if the models parse method uses this.app it will error. Beyond that it seems unnecessary to call parse in this use-case which is just constructing the fetch summary for the placeholder div.
We do want the model/collection to be instantiated using parse when the view is attached, so pass `{ parse: true }` explicitly from `parseOptions`
@saponifi3d @mattpardee @mrubens
=> make model/collection parsing an option in parseModelAndCollection

package.json, server/data_adapter/rest_adapter.js, shared/syncer.js, test/server/data_adapter/rest_adapter.test.js
Fix for: https://github.com/rendrjs/rendr/issues/416
Since most parsers can handle this syntax it seems like a better default, and `qs` parsers this syntax fine too.
@spikebrehm do you have any concerns about this?
=> changed the rest adapter to return array query parameters without indices

server/data_adapter/rest_adapter.js, test/server/data_adapter/rest_adapter.test.js
seems like there are cases where the query param is an empty object, checking to make sure it's not empty before adding a `?` too.
=> rest adapter fix

shared/fetcher.js, test/shared/fetcher.test.js
The fetcher was creating two collections for lazy loaded views, one without parameters and one with parameters.  This fix will make sure the first collection has the correct params, so it's not creating a second instance in the store when calling the `fetch` function when lazy loading the view.
=> make sure the fetcher creates the correct collection in the store.

shared/base/view.js
There was some jQuery cleanup of $ usages in 4d349499b72210a3ec96a49e7a9288c9d3300bd9, but a couple of usages got missed.  This fixes those missed $ usages.
=> Fix some missed usages of $

shared/app.js, shared/fetcher.js, test/shared/fetcher.test.js
In AMD we need to call `App.start()` inside a callback on `bootstrapData` otherwise  `App.start()`  get called before the data get stored in the modelStore.
=> Add callback to bootstrapData

client/router.js, shared/base/router.js, test/shared/base/router.test.js
This PR will fix the loading of controllers for the AMD version.
Sample App's PR : https://github.com/rendrjs/rendr-examples/pull/15
=> Load controller from action for AMD version

shared/base/router.js, test/shared/base/router.test.js
- The controller was called with the wrong context.
- Some variable changes
- Added unit test 
- Unit test code cleanup
=> Call the controller method with the right context

shared/app.js, test/fixtures/app/template_adapter.js, test/shared/app.test.js
I'd like to be able to inject pre-`require`d modules for `templateAdapter` and `ClientRouter` so that I don't have to `expose` them through Browserify config, in order for Rendr to require them for me. These optional attribute values should enable that use case without breaking any existing usages.
=> Dependency injection

shared/app.js
I think this should fix the require issue and still keep the original functionality of injecting an instance of `ClientRouter`
=> [RFC] Fix require

server/router.js, test/server/router.test.js
this PR has two motivations/changes:
1. In order to modify our `Content-Type` header to specify a charset,  we had to unchain the `res.type('html')` in `getHandler()` ( `type`'ll overwrite anything that's already been set).
1. Added a new attribute to the routes object `headers` to allow any headers to be passed in per route.
=> allow routes to specify custom headers

server/middleware/initApp.js, server/server.js, server/viewEngine.js, test/server/middleware/initApp.test.js, test/server/server.test.js, test/server/viewEngine.test.js
This adds flexibility allowing us to use a base layout with a name different from `__layout`, which is currently hardcoded into `viewEngine`. 
Using a custom template name will be as simple as doing this during the Rendr server creation:
```
var server = rendr.createServer({
baseLayoutName: 'myTemplate'
});
```
Rendr-handlebars is already flexible enough to allow this.
=> Allow custom base layout name

shared/app.js, test/shared/app.test.js
Since https://github.com/rendrjs/rendr-handlebars/pull/51, rendr-handlebars allows a custom templateFinder as an option.
These changes allow to easily pass that in from the Rendr side, breaking down a little bit the App constructor into smaller pieces, allowing for easy overriding.
Thoughts?
=> allow template finder option to be passed in within template adapter initialization

shared/fetcher.js, test/shared/fetcher.test.js
- Sometimes we want always to pull back certain data (readFromCache: false), and sometimes we want it to be the default.  While, there could be a nested approach, this simplifies how to set it by specifying it in the fetch spec 
- Wrote tests
- Tested by using it in our own own app
With this PR:
**This would be possible**
``` js
module.exports = {
index: function(params, callback) {
var spec = {
collection: {
collection: 'Users',
params: params
}
};
this.app.fetch(spec, function(err, result) {
callback(err, result);
});
},
show: function(params, callback) {
var spec = {
model: {
model: 'User',
params: params,
readFromCache: false
},
repos: {
collection: 'Repos',
params: {
user: params.login
},
readFromCache: true // or omit for default
}
};
this.app.fetch(spec, function(err, result) { …
```
=> Added ability for each spec to set readFromCache to true/false

README.md, package.json, shared/app.js, test/fixtures/app/template_adapter.js
Add a template system to the defaults, with default value `handlebars` to go along with the default `templateAdapter: 'rendr-handlebars'`.
This would allow us to directly control the version of Handlebars or of the template system that we are using from the Rendr app, instead of being coupled to what's inside the template adapter module.
This needs another PR in `rendr-handlebars` to be merged: https://github.com/rendrjs/rendr-handlebars/pull/52
Thoughts?
=> inject a templateEngine param to the template adapter

shared/base/view.js, test/shared/base/view.test.js
When calling `this.app.router.redirectTo('some/path')` from the client, the rendering order of views in a parent-child view hierarchy is often not correct.
This is happening because in `_postRender` we call `attachChildViews` and then immediately trigger the `postRender` event, without waiting for `attachChildViews` itself to be completed.
In AMD environment, this often results in child views firing postRender before parent views, or in random order anyway. 
The solution is as simple as firing `postRender` only when the child views are attached, using a callback for it.
Please let me know if this is not clear. 
What do you think?
=> Fix view hierarchy rendering order when rendering from the client

shared/base/view.js, shared/fetcher.js, test/shared/base/view.test.js
This PR introduces the ability to use the option `fetch_options` when lazy-loading a view to pass options to the `.fetch` call.
Additionally, I noticed that the options that the `fetch` method sets by default (specifically `readFromCache` and `writeToCache`) are not being added to the model's `options` hash because the options provided are not being passed down to the `getModelOrCollectionForSpec` call.  I made the change here to pass those options along as well.
=> add ability to pass fetch_options for a lazy fetch

shared/base/view.js, test/shared/base/view.test.js
This opens up `writeToCache`, `readFromCache`, `ensureKeys`, etc to a lazy loaded view on a per spec basis. this also allows someone to lazy load a chunk with multiple models / collections in parallel.
=> allow someone to pass the *entire* fetch spec.  

client/router.js, test/client/router.test.js
in a situation where there was a link like
```html
<a href="/path/not/in/rendr/routes">stuff</a>
```
On the page at `www.example.com/user/123`.  The app would end up redirecting to:
```
www.example.com/user/123/path/not/in/rendr/routes
```
instead of
```
www.example.com/path/not/in/rendr/routes
```
due to the path that's passed to the client router _never_ having a leading slash.
If a link is known to not be in Rendr, you can add the `data-pass-thru` element to the link and everything will work properly.  We can't always do that since we have separate Rendr apps on `/foo` and `/bar`  that link to each other with shared code that shouldn't always be `data-pass-thru` links.  I also think that this PR matches the intent of the code.
I kinda think that this used to work, but may have changed …
=> Add a leading / to backbone route misses to prevent routes being appended

server/middleware/apiProxy.js, test/server/middleware/apiProxy.test.js
This would allow more flexibility into `apiProxy`, allowing the usage of the `x-http-method-override header`. Currently, if we try to to use Backbone's `emulateHTTP` option ( http://backbonejs.org/#Sync-emulateHTTP), the header set from the client is then discarded by the Rendr app.
=> allow x-http-method-override header to be passed in from the client request

shared/base/view.js, test/shared/base/view.test.js
Gives a bit more control over lazy loading views.  Allows us to give success / error handlers, rather than a `console.log`.
=> Add override points for success / error when lazy loading a view

shared/base/view.js
When using rendr with `requirejs` in AMD mode the child views are attached with `null` as parent on the first render. Because we are waiting for the module to be loaded . This change is to forcefully attach the views in series.
=> Attach views back in series instead of async

shared/base/view.js, test/shared/base/view.test.js
These are automatically unescaped whenever they are rendered to the DOM, so doing it here actually unescapes the content too many times, opening up a potential XSS vector, e.g. when displaying escaped HTML in a _block.
See rendrjs/rendr-handlebars#61 for a more detailed explanation
=> Don't unescape view options

shared/syncer.js, test/shared/syncer.test.js
It seems like there is a discrepancy with how URL encoding takes place.
Given a model `var UserModel = BaseModel.extend({urlRoot: '/users'})`, we can fetch it with a spec `{model: 'UserModel', params: {id: 'президент'}}` and the URL fetched will be `/users/%D0%BF%D1%80%D0%B5%D0%B7%D0%B8%D0%B4%D0%B5%D0%BD%D1%82` thanks to [Backbone's `url` method](http://backbonejs.org/docs/backbone.html#section-90) applying a `encodeURIComponent` to the ID.
With a collection `var UserOrderCollection = BaseCollection.extend({url: '/users/:user_id/orders'})` and a fetch spec `{collection: 'UserOrderCollection', params: {user_id: 'президент'}}`, no encoding is applied and so the URL requested is `/users/президент/orders`.
Upgrading from Node 0.10.30 to a later version has revealed this for us. It seems that …
=> URI encode interpolated parameter value
